name = "quasimorph-dive-ladder"
main = "src/index.ts"
compatibility_date = "2025-07-01"

[[d1_databases]]
binding = "DB"
database_name = "dive-ladder"
database_id = "d3368c22-6e78-4edd-bb0e-e0117eabd722"

[vars]
ALLOWED_MOD_VERSIONS = "0.4.0"
MAX_SUBMITS_PER_DAY = "25"
