<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Mechs</AssemblyName>
    <RootNamespace>Mechs</RootNamespace>
    <UniqueModName>Mechs</UniqueModName>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modmanifest.json" />
    <None Include="thumbnail.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(QuasimorphManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(QuasimorphManagedDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
