<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RoguelikeMode</AssemblyName>
    <RootNamespace>RoguelikeMode</RootNamespace>
    <!-- Must match UniqueModName in modmanifest.json. Letters, digits and underscore only. -->
    <UniqueModName>RoguelikeMode</UniqueModName>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="modmanifest.json" />
    <None Include="thumbnail.png" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(QuasimorphManagedDir)\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(QuasimorphManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
